const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),{default:AxeBuilder}=require('@axe-core/playwright');
const T=require('../assets/js/terminal-model.cjs'.replace('.cjs','.js'));
assert.equal(T.resolvePath('../../../../etc','/proyectos'),'/etc');assert.equal(T.resolvePath('~/proyectos/../perfil.md'),'/perfil.md');assert.deepEqual(T.tokens('cat "perfil.md"'),['cat','perfil.md']);assert.throws(()=>T.tokens('cat "perfil'));
const base=(process.env.TEST_SITE_URL||'http://127.0.0.1:4000').replace(/\/$/,''),captures=path.join(__dirname,'../.impeccable/review');fs.mkdirSync(captures,{recursive:true});
(async()=>{const browser=await chromium.launch();try{
 const context=await browser.newContext({viewport:{width:1440,height:950}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/terminal.html');await page.locator('#console-form:not([hidden])').waitFor();await page.waitForTimeout(700);await page.screenshot({path:path.join(captures,'terminal-desktop.png')});
 const input=page.locator('#console-input'),out=page.locator('#console-output'),last=()=>page.locator('.terminal-result').last();
 async function cmd(value){await input.fill(value);await input.press('Enter');}
 await cmd('ls');assert.match(await last().innerText(),/proyectos\//);await cmd('cd proyectos');assert.equal(await page.locator('#prompt-path').innerText(),'~/proyectos');await cmd('pwd');assert.equal(await last().innerText(),'/home/jorge/proyectos');
 await input.fill('cat azi');await input.press('Tab');assert.equal(await input.inputValue(),'cat azimut.md');await input.press('Enter');assert.match(await last().innerText(),/servicios de respaldo reciben/);assert.match(page.url(),/proyecto=azimut/);
 await page.waitForTimeout(250);await page.screenshot({path:path.join(captures,'terminal-project.png')});
 await cmd('cd ../formacion');await cmd('cat bootcamp.md');assert.match(await last().innerText(),/Bootcamp/);await cmd('cd ~');await cmd('cat "perfil.md"');assert.match(await last().innerText(),/Jorge Ulloa/);
 await cmd('cd ../../../../../');assert.equal(await page.locator('#prompt-path').innerText(),'~');await cmd('cat /missing');assert.match(await last().innerText(),/no existe/);assert.equal(await page.locator('#exit-code').innerText(),'exit 1');
 await cmd('cat proyectos');assert.match(await last().innerText(),/es una carpeta/);await cmd('cat "perfil');assert.match(await last().innerText(),/cerrar una comilla/);await cmd('<img src=x onerror=alert(1)>');assert.equal(await out.locator('img').count(),0);assert.equal(await page.locator('#exit-code').innerText(),'exit 127');
 await input.fill('abrir azi');await input.press('Tab');assert.equal(await input.inputValue(),'abrir azimut');await input.press('Enter');await input.press('ArrowUp');assert.equal(await input.inputValue(),'abrir azimut');await input.press('ArrowDown');assert.equal(await input.inputValue(),'');
 await input.fill('pendiente');await input.press('Control+c');assert.equal(await input.inputValue(),'');assert.equal(await page.locator('#exit-code').innerText(),'exit 130');await input.press('Control+l');assert.equal(await page.locator('.terminal-entry').count(),0);
 await cmd('tree');assert.match(await last().innerText(),/formacion\//);await cmd('help cd');assert.match(await last().innerText(),/cd proyectos/);await cmd('history');assert.match(await last().innerText(),/cat bootcamp.md/);
 await cmd('abrir azimut');await page.locator('#terminal-map').click();assert.match(page.url(),/proyecto=azimut/);await page.locator('#conversation[open]').waitFor();assert.match(await page.locator('#dialog-content').innerText(),/servicios de respaldo/);
 await page.goto(base+'/terminal.html?lugar=constructor');await page.locator('#console-form:not([hidden])').waitFor();await cmd('ir constructor');assert.equal(await page.locator('#exit-code').innerText(),'exit 1');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});await cmd('help');await page.waitForTimeout(260);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);const a=await new AxeBuilder({page}).analyze();assert.deepEqual(a.violations.map(v=>v.id),[],'axe '+width);}
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/terminal.html');await page.waitForTimeout(700);await page.screenshot({path:path.join(captures,'terminal-mobile.png')});await cmd('cd proyectos');await cmd('cat azimut.md');await page.waitForTimeout(260);await page.screenshot({path:path.join(captures,'terminal-mobile-project.png')});
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.documentElement.dataset.terminalMotion==='off');assert.equal(await page.locator('html').getAttribute('data-terminal-motion'),'off');assert.equal(await page.locator('.terminal-entry').last().evaluate(e=>getComputedStyle(e).animationName),'none');
 const nojs=await browser.newPage({javaScriptEnabled:false});await nojs.goto(base+'/terminal.html');await nojs.locator('.terminal-index summary').click();assert.equal(await nojs.locator('.terminal-index a:visible').count(),6);
 await page.goto(base+'/');assert.equal((await page.locator('h1').innerText()).replace(/\s+/g,' '),'Geografía para leer el mundo.');assert(await page.locator('.hero').evaluate(e=>e.compareDocumentPosition(document.querySelector('.exp-entrypoint'))&Node.DOCUMENT_POSITION_FOLLOWING));assert.match(await page.locator('.exp-entrypoint').innerText(),/Si tú tampoco/);
 assert.deepEqual(errors,[]);console.log('PASS terminal filesystem, quoting, completion, history, cancellation, errors/XSS, guidance, handoff, responsive, reduced, noJS, axe and classic-first');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
